server:
  host: http://localhost
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true

kakao:
  client:
    id: 22998ce270e005c3da0bd1771cb89092
    secret: r3gsmBEqgmA1hNYGTtYHzv1Bl7gP3yVU
  redirect-uri: http://localhost:8080/api/oauth/authenticate
  base-uri:
    connect: https://kauth.kakao.com/oauth/authorize?
    get-token: https://kauth.kakao.com/oauth/token
    token-info: https://kapi.kakao.com/v1/user/access_token_info
    user-info: https://kapi.kakao.com/v2/user/me
    token-update: https://kauth.kakao.com/oauth/token
    log-out: https://kapi.kakao.com/v1/user/logout

spring:
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: true
    hibernate:
    ddl-auto: create
    properties:
      hibernate:
        format-sql: true

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #   mail:
    #     host: smtp.naver.com
    #     port: 465
    #     username: arch_engineer@naver.com
    #     password: 1q2w3e4r5t!
    #     properties:
    #       mail:
    #         smtp:
    #           starttls:
    #             enable: true
    #           auth: true
    #           ssl:
    #             trust: smtp.naver.com
    #             enable: true
    #
    #   redis:
    #     host: 127.0.0.1
    #     port: 6379
    #     password: 1q2w3e4r5t!
    #
#
#   datasource:
#     driver-class-name: org.h2.Driver
#     url: jdbc:h2:mem:testdb
#     username: sa
#     password:

